### ISSUE TITLE
[Bug]: enum columns don't work in v3

### ISSUE THREAD

**Issue by nikosid** [rappasoft/laravel-livewire-tables#1434]
### What happened?

After upgrade to v3 I get the error:
`Rappasoft\LaravelLivewireTables\Views\Column::getContents(): Return value must be of type Illuminate\Support\HtmlString|Rappasoft\LaravelLivewireTables\Exceptions\DataTableConfigurationException|Illuminate\Contracts\Foundation\Application|Illuminate\Contracts\View\Factory|Illuminate\Contracts\View\View|string|null, App\Enums\UrlSource returned`

This happens because I have this column configured:
`Column::make('Source', 'source')->sortable(),`

In my model there is this cast:
```
protected $casts = [
        'source' => UrlSource::class,
    ];
```
and class UrlSource looks like this:
```
<?php

namespace App\Enums;

enum UrlSource: string
{
    case WEB = 'web';
    case API = 'api';
}
```

### Package Version

v3.0.0.-beta.4

### PHP Version

8.2.x

### Laravel Version

10.28.0

### Theme

None

### Notes

This worked in version 2*

### Error Message

Rappasoft\LaravelLivewireTables\Views\Column::getContents(): Return value must be of type Illuminate\Support\HtmlString|Rappasoft\LaravelLivewireTables\Exceptions\DataTableConfigurationException|Illuminate\Contracts\Foundation\Application|Illuminate\Contracts\View\Factory|Illuminate\Contracts\View\View|string|null, App\Enums\UrlSource returned

**Comment by lrljoe** [comment]
So I've added the return type hint in, so that you won't receive the error, that's in v3-develop now, and will go into a new beta release in the next day or two.

Interested to know your use case for it though, and whether an EnumColumn or similar would be useful going forward (for example - allowing you to specify which method you want to call on the column).
