### ISSUE TITLE
Export to PDF or CSV buttons

### ISSUE THREAD

**Issue by pushpak1300** [rappasoft/laravel-livewire-tables#15]
It will be great if there is button for export to pdf and csv like datatables.

https://github.com/kdion4891/laravel-livewire-tables/issues/23
I have created issue there but i think it is not activly maintained.

**Comment by pushpak1300** [comment]
@rappasoft

**Comment by rappasoft** [comment]
Definitely a good idea, but I have a lot of important stuff to do before any features like that. Like to write tests to make sure it's stable.

**Comment by pushpak1300** [comment]
Okay, No Problem @rappasoft  .I have implemented that feature in my local envoirment. so once your package is ready for production use.Please let me know .I can contribute to this feature.

**Comment by rappasoft** [comment]
It works well? It would definitely be easier if it was a PR vs me having to figure it out now.

**Comment by pushpak1300** [comment]
Yes,it works fine.
But problem is how we want to export data i.e on client side or server side using [Larvel Excel Package](https://docs.laravel-excel.com) .
Which one you would prefer?
I have working Example of Client-Side using  table2csv library.

**Comment by rappasoft** [comment]
It depends. If you have pagination enabled and you're looking at 10 out of 100 rows, client side could only export those 10 rows you're looking at while server side can export any amount.

Though i'm assuming you'd only want the ones you're looking at because you've narrowed down your search, but if you wanted an export all button you'd need Laravel Excel.

I think jquery datatables does it client side.

**Comment by pushpak1300** [comment]
Yes Datatables does it in client side.

**Comment by pushpak1300** [comment]
Okay ,I will make PR.
