### ISSUE TITLE
[Bug]: Livewire component in Datatable: Snapshot missing on Livewire component with id...

### ISSUE THREAD

**Issue by mLicorn** [rappasoft/laravel-livewire-tables#1644]
### What happened?

I'd like to use Livewire components in an array.
My initial requirement is to display a hidden row when I click on an icon in a column. This row loads another table.

I managed to implement this with Livewire 2, but since version 3 I've been getting an error when I try to sort by a column: '_Snapshot missing on Livewire component with id._'.
The interior of the component is deleted, leaving only the wire:id attribute.

![error-min](https://github.com/rappasoft/laravel-livewire-tables/assets/10559840/72267262-f05d-4adf-9422-cc13ad8fcb88)
![html-min](https://github.com/rappasoft/laravel-livewire-tables/assets/10559840/91f2b037-5cc9-4d11-97af-9fd298a5cd6b)

I've simplified the test by simply trying to display a Livewire component in a column.
After several tests, **I can't use a Livewire component in the datatable.**.

I'm probably doing something wrong, but I can't work out what.

### How to reproduce the bug

1. Create a new Laravel project: migrate and seed database
2. Install Livewire 3
3. Install Laravel Livewire Tables
4. Create TestChild component
```php
<?php

namespace App\Livewire;

use Livewire\Component;

class TestChild extends Component
{
    public int|string|null $index = null;
    public int|string|null $parent = null;

    public function render()
    {
        return view('livewire.test-child');
    }
}
```
```blade
<div wire:key="test-child-component-{{ $parent }}-{{ $index }}">CHILD {{ $index }} !!</div>
``` 
5. Create UsersTable
```php
<?php

namespace App\Livewire;

use App\Models\User;
use Rappasoft\LaravelLivewireTables\DataTableComponent;
use Rappasoft\LaravelLivewireTables\Views\Column;

class UsersTable extends DataTableComponent
{
    protected $model = User::class;

    public function configure(): void
    {
        $this->setPrimaryKey('id');
    }

    public function columns(): array
    {
        return [
            Column::make('ID', 'id')
                ->sortable()
                ->searchable(),

            Column::make('Name')
                ->sortable()
                ->view('datatables.columns.test')
                ->searchable(),

            Column::make('E-mail', 'email')
                ->sortable()
                ->searchable(),
        ];
    }
}
``` 
6. Create view: datatables.columns.test
```blade
@aware(['tableName'])
@props(['row'])


<div wire:key="column-test-child-{{ $tableName . '-' . $row->id }}">
  <livewire:test-child
    index="{{ $row->id }}"
    :parent="$tableName"
  />
</div>
``` 
7. Display Datatable in Welcome page
```blade
<div><livewire:users-table /></div>
``` 
8. Sort by Name: error

![step-1-min](https://github.com/rappasoft/laravel-livewire-tables/assets/10559840/82d3be6e-1da9-484e-9e81-353ca908830a)
![step-2-min](https://github.com/rappasoft/laravel-livewire-tables/assets/10559840/58c5bf3a-08e0-48ca-b635-06a7717d9f40)

### Package Version

3.2.0

### PHP Version

8.1.x

### Laravel Version

10.40.0

### Alpine Version

3.13.3

### Theme

Tailwind 3.x

### Notes

I've left all the default settings except for the database connection.

### Error Message

Uncaught Snapshot missing on Livewire component with id: `...`

**Comment by lrljoe** [comment]
Hmm, so you're loading in a Livewire Component as the content of a Column, and getting that error?

Which version of Livewire are you using out of interest, so that I can try to replicate it properly.

Worth noting - it will always be sluggish trying to have 25/50/100 Livewire Components on a page, that's a Livewire things rather than a package thing.
What's your end goal with it, as there may be a neater solution.  It's one of the reasons we didn't introduce the Livewire Component Column, as on larger tables (100/200 rows in view), it was really low performance when re-rendering.

**Comment by mLicorn** [comment]
Thanks for your reply.

My first goal was to create a sub-row that loads another Datatable on demand (by clicking on an icon in a column).

Finally I created a component outside the Datatable that dynamically inserts and displays the row with AlpineJS.

**Comment by maikezan** [comment]
Hello, i've stumbled across the same issue. We know that LivewireComponentColumn is currently  not recommended, but we are looking for a way to dynamically update column values without refreshing the entire table (we have data that may update frequently through several events and refreshing the entire table would result in a very bad experience).

We tried different ways of using a livewire component inside a column (Column, Component, ViewComponent etc), but so far only the LivewireComponentColumn renders correctly and reacts to the events.

The issue is triggered when the table rerenders due to any operation like reordering, bulk actions, changing page size etc.

What i can add is that if there is only 1 LivewireComponentColumn, everything works fine. The moment we add a second one, the 

`Uncaught Snapshot missing on Livewire component with id`

error is thrown.
