### ISSUE TITLE
[Bug]: Loss of Selections After Search 

### ISSUE THREAD

**Issue by gbaltazar** [rappasoft/laravel-livewire-tables#1702]
### What happened?

Error description: I'm making a multiple selection of items to later perform a Bulk operation with them. I select a first item, then perform a search to select the second one, but the previous selection I had made is cleared. 

### How to reproduce the bug

I first try searching for the items I want to select, choose one of them, then upon searching to select another, the previous selection is erased. Is it possible to maintain the selection I had made after performing a search in the component?

### Package Version

2.15

### PHP Version

8.1.x

### Laravel Version

10.0

### Alpine Version

3.13.9

### Theme

Bootstrap 4.x

**Comment by ivanmar01** [comment]
I can confirm that bug exists also in latest v3 version.

**Comment by lrljoe** [comment]
To be honest, it's more intentional than being a bug.

Having something "selectable", but not visible seems odd to my mind.

E.g. you select the user "Bob" after searching for users "Bo".
Then you search for "Jo" and select "Joe".
Having "Bob" still selected, despite not being visible (and thus not deselectable) seems like not great UX.

If there's something I'm missing, then we can look at adding in a config option to enable/disable a different behaviour, but would need to know how widespread the desire is for it so that I can prioritise it.

**Comment by lrljoe** [comment]
Quick update, I've added in some toggles, but it'll be at least a week (ish) for it to make it into v3, as I need to write tests & docs for it.

**Comment by ivanmar01** [comment]
Thanks for reply. 
My users have long list of equipment and they are searching  it by serial number.  After selecting it, selection will bi added to final document. That is my scenario and it will be much easier to remember selected items.
All the best!

**Comment by lrljoe** [comment]
Okay, so this is a Feature Request for the option to enable/disable the clearing of Selected Items on Search (retaining it by default as enabled).

It shouldn't be difficult to deliver, and I imagine this should then make it into the next release.  I'm closing this issue, and created a Feature Request (#1759 ) to track this.
