### ISSUE TITLE
[Bug]: NumberFilter doesn't work

### ISSUE THREAD

**Issue by G4Zz0L1** [rappasoft/laravel-livewire-tables#2030]
### What happened?

The `NumberFilter` has stopped working since version 3.4.15.
I'm including the relevant code snippet below (GitHub doesn't allow diff links to a single file):

![image](https://github.com/user-attachments/assets/55a6bd57-4f37-49f6-8ca3-66b382faef3f)

Basically, filter values are always sent as strings from the frontend, so the `NumberFilter` will always return false.
Changing it to `TextFilter` works, but then we lose the `min` and `max` parameters, which makes it less useful.
It might be best to roll back that file, as `is_numeric` should be more than sufficient—especially since `type="number"` should theoretically prevent non-numeric characters from being entered.
Thanks in advance!

### Package Version

3.4.22

### PHP Version

8.3.x

### Laravel Version

11.30.0

### Alpine Version

3.14.3

### Theme

Tailwind 3.x

**Comment by lrljoe** [comment]
#1999  - Is the issue being tracked for this bug, which is now fixed in dev-development.  Please do test against the development branch, and let me know if the issue persists.

I plan to merge development into master in the next few days, just haven't had time recently do properly test everything (which we try to do before any release).
