### ISSUE TITLE
Header Alignment

### ISSUE THREAD

**Issue by slakbal** [rappasoft/laravel-livewire-tables#419]
Hi,

I have a stock standard setup without any custom styling etc.

As soon as a column is sortable the header doesn't align and the sorting caret icons are below the header.

What could the issue be?

![image](https://user-images.githubusercontent.com/4387265/126951891-687f95a4-b013-435d-8658-a6503a5a9296.png)

**Comment by rappasoft** [comment]
I'd imagine you don't have the flex classes loaded in your stylesheet.

**Comment by nvi9** [comment]
@slakbal I've had a similar problem when I started using this library, if you're using Tailwind CSS it can be because of its purging functionality described here: https://github.com/rappasoft/laravel-livewire-tables/wiki/Installation-&-Configuration#tailwind-purge

After you've completed the setup, it is required to rebuild assets to have the newly included class names included (eg. with `yarn dev`).

**Comment by rappasoft** [comment]
Flex default should be row. As you can see on the [demo](https://tables.laravel-boilerplate.com/tailwind) we're loading tailwind fully via CDN and it's working properly.

<img width="1201" alt="Screen Shot 2021-08-24 at 11 10 58" src="https://user-images.githubusercontent.com/6026504/130642314-4ef437d9-6f8d-4fec-b648-60b60452e616.png">

**Comment by slakbal** [comment]
Thanks! @rappasoft I'll search for the issue! Much appreciated!
