### ISSUE TITLE
row view at top of individual rows

### ISSUE THREAD

**Issue by rogerad** [rappasoft/laravel-livewire-tables#442]
hi i am **using row view** and am adding a **single button ABOVE the row views**
 i cannot add it as it appears 7 times depending on the number of columns used
 ```
 <button wire:click="addContact">xxentrydashSubmit</button>
   
    <x-livewire-tables::table.cell>
  {{ $row->id }}


    </x-livewire-tables::table.cell>
<img width="755" alt="rappa-Screenshot 2021-08-21 160802" src="https://user-images.githubusercontent.com/18638656/130312414-2b18ef50-26cc-4ea6-b811-d467f0670c1a.png">

```

**Comment by Majkie** [comment]
This won't work because row view is in foreach of $rows. Check code - [Row view](https://github.com/rappasoft/laravel-livewire-tables/blob/master/resources/views/tailwind/includes/table.blade.php#L89)

You can make for example file index.blade.php which would look like this. This means blade file containing table and button above the search (That's exactly the way I make these kind of create/export buttons). Check the screenshot below the code.

```blade
<div>
  <button wire:click="addContact">xxentrydashSubmit</button>
  
  <livewire:packages.data-table />
</div>
```

<img width="1239" alt="Screenshot 2021-08-21 at 17 17 41" src="https://user-images.githubusercontent.com/37813691/130326458-c8010a8c-94b9-45ee-b267-fbc1c1667deb.png">


Hope this works best for you!

**Comment by rogerad** [comment]
Thank you 

 I will try this out
