### ISSUE TITLE
Polymorphic relationships not working in v2.

### ISSUE THREAD

**Issue by ddkpdev** [rappasoft/laravel-livewire-tables#749]
Polymorphic relationships used to work in v1 but they don't work in v2. 

This worked in V1: 

`Column::make('Item #', 'inventoryable.item_number')
   ->searchable(),
Column::make('Name', 'inventoryable.name')
    ->searchable()`

"inventoryable" is the name of the morphTo() relationship on the Inventory model. 

However, in v2 it throws the following error: 

`SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'inventories' (SQL: select count(*) as aggregate from inventories left join inventories on inventories.inventoryable_id = inventories.)`

Only way I found to make this work was to create a column and then using the label method pull a custom view, parse it the model and grab the relationship values from the view. This, however, disables the possibility for searching and sorting the columns.

`
            Column::make('Item #')
                ->label(
                    fn($row, Column $column) => view('inventories.datatable.item-number-cell')->withRow(Inventory::findOrFail($row->id))
                ),
`

I notice the documentation says, that only belongsTo and hasOne relationships are supported right now. Any time frame on adding more relationship types or are there any workarounds?

This package is amazing 💪🏼

**Comment by rappasoft** [comment]
I don't have a good enough grasp on the internals of Eloquent to really figure it out on my own which is why I only got that far. If you know of a package or example code that supports all of the relationships, I'll gladly use that as an example. Or if you know better than I, most of the code for this stuff is in this file: https://github.com/rappasoft/laravel-livewire-tables/blob/master/src/Traits/WithData.php

I tried to keep it all in one place.

**Comment by inmanturbo** [comment]
>package or example code that supports all of the relationships

Just putting this here for my own future reference:
https://spatie.be/docs/laravel-query-builder/v5/features/including-relationships

Also query strings seem to be getting a rewrite in Livewire v3??
