### ISSUE TITLE
Table not refreshing when selecting a filter

### ISSUE THREAD

**Issue by siebsie23** [rappasoft/laravel-livewire-tables#873]
Hello,

Everything was working normally until I upgraded from 1.* to 2.*.
After compiling all the files on a Mac using composer install and npx mix the tables don't refresh when applying a new filter, also there is no white overlay visible.

When installing and compiling everything on a Windows machine using the exact same code the tables refresh as they should when applying different filters and also show the white overlay.

There are no errors visible in the dev console or in the logs.

**Comment by siebsie23** [comment]
UPDATE:
It seems to also not be working when compiled on Windows. It does show the white refresh overlay but it's still not refreshing correctly.
If `$this->setRefreshTime(2000);` is set it will refresh correctly after the defined time has passed, but it's not auto-refreshing when a new filter has been selected.

**Comment by masetto** [comment]
I have the same problem, @siebsie23 yhy did you close the issue?

**Comment by siebsie23** [comment]
> I have the same problem, @siebsie23 why did you close the issue?

For me the issue was my query. I was adding a 'where' when there was no filter selected and tried removing that when the filter 'Show all' was selected. This worked in 1.* but broke in 2.*.

Now I just set a default filter when visiting the tables page and everything is working correctly

**Comment by bdelamatre** [comment]
In case anyone else has this issue, I was able to fix this by manually firing the refresh event use a livewire lifecycle hook.

```
    public function updated($column, $value): void
    {
        parent::updated($column, $value);
        $this->emit('refreshDatatable');
    }
```

**Comment by lrljoe** [comment]
@bdelamatre 
This definitely isn't happening in any of my demo environments for v2

If you're having a problem, then please raise an Issue, or drop into the Discord to explain it, as I'm not seeing any issues in any of my demo environments.

It's worth noting, that if you're using the builder() function to apply the filters, then you may experience a lifecycle delay, and it works more smoothly to apply the filter methods to the filter itself.

**Comment by bdelamatre** [comment]
@lrljoe

Thanks for the suggestion. I am using filters inside the builder method, but I can't say if this is related or not. I am wrapping up a largeish upgrade from 1.x to 2.x (as the original reporter indicated as well), so perhaps there is something to that aspect here. I haven't dug deeply into the issue yet since the workaround I published appears to work well and I will follow-up as soon as I am able.

I will note one more aspect of the filter behavior, it's not that the filter never applies it's that it's always one step behind. Say for example that I have a state filter:

- Select state X, no filter is applied
- Select state Y, state X is filtered
- Select state Z, state Y is filtered
- etc.

**Comment by lrljoe** [comment]
If you share your full table component I'll see if anything is obviously wrong!

It certainly shouldn't behave like that.
