### ISSUE TITLE
Help to personalize individual TD class

### ISSUE THREAD

**Issue by Geovanek** [rappasoft/laravel-livewire-tables#95]
Hi,
I didn't understand how I can individually customize each TD class
With this?

`public function setTableDataClass($attribute, $value): ?string`

**Comment by ConnorHowell** [comment]
The classes get set to the return value of that function, since the function gets passed the attribute name & it's current value you can use something similar to the below to set the classes. This is a very basic example as you could add some conditional formatting based on the columns current value if you wish.
```php
public function setTableDataClass($attribute, $value): ?string
{
    switch ($attribute) {
        case 'id':
            return 'text-left font-w700';
        case 'date_updated':
        case 'actions':
            return 'text-center';
        default:
            return null;
    }
}
```

**Comment by Geovanek** [comment]
Thanks,
Now it's clear how to use it.
